keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.123, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.252, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.75, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.75, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(2.75, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(1.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)

finishedSong()