keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.167, bpm)
keypress("*", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
rest(0.167, bpm)
keypress("*", x, bpm)
rest(0.167, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
rest(0.167, bpm)
keypress("7", x, bpm)
rest(0.167, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("7", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("b", x, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("b", x, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("b", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("b", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("b", x, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("L", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("c", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("V", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("!", x, bpm)
rest(2, bpm)
keypress("c", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(1, bpm)
keypress("V", x, bpm)
rest(1, bpm)
keypress("C", x, bpm)
rest(1, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(1, bpm)
keypress("V", x, bpm)
rest(1, bpm)
keypress("C", x, bpm)

finishedSong()