keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(3, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(3, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(3, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)

finishedSong()