keypress("@", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
rest(2, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(4, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("%", x, bpm)
rest(4, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(4, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("@", x, bpm)
rest(3, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(4, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(8, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(12, bpm)
keypress("@", x, bpm)

finishedSong()