keypress("$", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(3, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(1.75, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("c", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(1.75, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("c", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(3, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(3, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("J", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)

finishedSong()