rest(5, bpm)
keypress("J", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.083, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("o", x, bpm)
rest(0.917, bpm)
keypress("j", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.625, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("*", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.083, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("P", x, bpm)
rest(0.417, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.083, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("o", x, bpm)
rest(0.917, bpm)
keypress("j", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("*", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("*", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("G", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("f", x, bpm)
keypress("s", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("@", x, bpm)
rest(0.125, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)

finishedSong()