keypress("d", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("v", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("v", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("v", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("v", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("v", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("v", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(2, bpm)
keypress("j", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)

finishedSong()