keypress("I", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(4, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(2, bpm)
keypress("$", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(3, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
rest(7, bpm)
keypress("$", x, bpm)
rest(6, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(2, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
rest(0.131, bpm)
keypress("j", x, bpm)
rest(0.133, bpm)
keypress("L", x, bpm)
rest(0.135, bpm)
keypress("C", x, bpm)
rest(1.6, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(2, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("j", x, bpm)
rest(0.131, bpm)
keypress("L", x, bpm)
rest(0.133, bpm)
keypress("C", x, bpm)
rest(0.135, bpm)
keypress("b", x, bpm)
rest(1.6, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(6, bpm)
keypress("G", x, bpm)
rest(0.131, bpm)
keypress("j", x, bpm)
rest(0.133, bpm)
keypress("L", x, bpm)
rest(0.135, bpm)
keypress("C", x, bpm)
rest(3.6, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.129, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.371, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(2, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(2, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
rest(0.131, bpm)
keypress("e", x, bpm)
rest(0.131, bpm)
keypress("T", x, bpm)
rest(0.137, bpm)
keypress("I", x, bpm)

finishedSong()