keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("3", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("n", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.154, bpm)
keypress("I", x, bpm)
rest(0.156, bpm)
keypress("O", x, bpm)
rest(0.156, bpm)
keypress("S", x, bpm)
rest(0.033, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.154, bpm)
keypress("O", x, bpm)
rest(0.156, bpm)
keypress("S", x, bpm)
rest(0.19, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.154, bpm)
keypress("I", x, bpm)
rest(0.156, bpm)
keypress("O", x, bpm)
rest(0.156, bpm)
keypress("S", x, bpm)
rest(0.033, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.154, bpm)
keypress("I", x, bpm)
rest(0.156, bpm)
keypress("S", x, bpm)
rest(0.19, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(2.4, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1.6, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(1.6, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(1.6, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(1.6, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1.6, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(1.6, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.8, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.8, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.8, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.8, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.8, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("5", x, bpm)
rest(0.8, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.8, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.8, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.8, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(2.4, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.8, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(1.6, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(1.6, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(1.6, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(1.6, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(1.6, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(1.6, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(2.4, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.8, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(1.6, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(1.6, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(1.6, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(1.6, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
rest(1.6, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(1.6, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.8, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.8, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.8, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.8, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.8, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.8, bpm)
keypress("4", x, bpm)
rest(0.8, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(0.8, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.8, bpm)
keypress("4", x, bpm)
rest(0.8, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1.6, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(1.6, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.8, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.8, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.8, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("5", x, bpm)
rest(0.8, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.8, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.8, bpm)
keypress("O", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.8, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.8, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(3.2, bpm)
keypress("B", x, bpm)
keypress("D", x, bpm)
rest(0.6, bpm)
keypress("P", x, bpm)
rest(0.6, bpm)
keypress("o", x, bpm)
rest(0.6, bpm)
keypress("V", x, bpm)
keypress("P", x, bpm)
rest(0.6, bpm)
keypress("v", x, bpm)
keypress("D", x, bpm)
rest(0.6, bpm)
keypress("P", x, bpm)
rest(0.6, bpm)
keypress("c", x, bpm)
keypress("o", x, bpm)
rest(0.6, bpm)
keypress("P", x, bpm)
rest(0.6, bpm)
keypress("Z", x, bpm)
keypress("D", x, bpm)
rest(0.6, bpm)
keypress("s", x, bpm)
rest(0.6, bpm)
keypress("c", x, bpm)
keypress("O", x, bpm)
rest(0.6, bpm)
keypress("s", x, bpm)
rest(0.6, bpm)
keypress("v", x, bpm)
keypress("D", x, bpm)
rest(0.6, bpm)
keypress("P", x, bpm)
rest(0.6, bpm)
keypress("Z", x, bpm)
keypress("o", x, bpm)
rest(0.6, bpm)
keypress("P", x, bpm)
rest(0.6, bpm)
keypress("m", x, bpm)
keypress("D", x, bpm)
rest(0.6, bpm)
keypress("m", x, bpm)
keypress("s", x, bpm)
rest(0.6, bpm)
keypress("m", x, bpm)
keypress("O", x, bpm)
rest(0.6, bpm)
keypress("m", x, bpm)
keypress("D", x, bpm)
rest(0.6, bpm)
keypress("B", x, bpm)
keypress("h", x, bpm)
rest(0.6, bpm)
keypress("D", x, bpm)
rest(0.6, bpm)
keypress("P", x, bpm)
rest(0.6, bpm)
keypress("V", x, bpm)
keypress("g", x, bpm)
rest(0.6, bpm)
keypress("J", x, bpm)
keypress("v", x, bpm)
keypress("h", x, bpm)
rest(0.9, bpm)
keypress("l", x, bpm)
rest(0.9, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("H", x, bpm)
rest(1.8, bpm)
keypress("Z", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("z", x, bpm)
rest(0.154, bpm)
keypress("Z", x, bpm)

finishedSong()