rest(1, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("E", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.092, bpm)
keypress("w", x, bpm)
rest(0.092, bpm)
keypress("E", x, bpm)
rest(0.567, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.092, bpm)
keypress("o", x, bpm)
rest(0.408, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.092, bpm)
keypress("o", x, bpm)
rest(0.408, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.119, bpm)
keypress("O", x, bpm)
rest(0.119, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.478, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.119, bpm)
keypress("O", x, bpm)
rest(0.119, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.478, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.478, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.478, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.478, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.478, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.478, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.478, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.478, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.478, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("w", x, bpm)
rest(0.119, bpm)
keypress("O", x, bpm)
rest(0.119, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("E", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.478, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("%", x, bpm)
rest(0.478, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.478, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("E", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("E", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("E", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.478, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.478, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("%", x, bpm)
rest(0.478, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.478, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("E", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.478, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("E", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.478, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("E", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.478, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.478, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
keypress("9", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("E", x, bpm)
rest(0.478, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.478, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.239, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.478, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.239, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.239, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.239, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.478, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.239, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.478, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.239, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.478, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.478, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.239, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.478, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.239, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.478, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("h", x, bpm)
keypress("!", x, bpm)
rest(0.478, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.478, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("5", x, bpm)
rest(0.478, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.239, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.478, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.239, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.478, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("h", x, bpm)
keypress("!", x, bpm)
rest(0.478, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.478, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("t", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.239, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("4", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.478, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("%", x, bpm)
rest(0.478, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("^", x, bpm)
rest(0.478, bpm)
keypress("^", x, bpm)
rest(0.478, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("*", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("E", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("q", x, bpm)
rest(0.478, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.239, bpm)
keypress("q", x, bpm)
rest(0.478, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.239, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.239, bpm)
keypress("W", x, bpm)
rest(0.239, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.239, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("4", x, bpm)
rest(0.478, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
rest(0.239, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("q", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
rest(0.478, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.478, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.119, bpm)
keypress("O", x, bpm)
rest(0.119, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.478, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.119, bpm)
keypress("O", x, bpm)
rest(0.119, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.119, bpm)
keypress("O", x, bpm)
rest(0.119, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.478, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.119, bpm)
keypress("O", x, bpm)
rest(0.119, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
rest(0.239, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("D", x, bpm)
rest(0.239, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.239, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)

finishedSong()