keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
rest(0.102, bpm)
keypress("P", x, bpm)
rest(0.898, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.75, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("P", x, bpm)
rest(0.398, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("P", x, bpm)
rest(0.398, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.75, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.875, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.131, bpm)
keypress("G", x, bpm)
rest(0.133, bpm)
keypress("Z", x, bpm)
rest(0.235, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.044, bpm)
keypress("Q", x, bpm)
rest(0.044, bpm)
keypress("r", x, bpm)
rest(0.163, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.131, bpm)
keypress("C", x, bpm)
rest(0.119, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.015, bpm)
keypress("n", x, bpm)
rest(0.235, bpm)
keypress("!", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("C", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.044, bpm)
keypress("Q", x, bpm)
rest(0.044, bpm)
keypress("r", x, bpm)
rest(0.163, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.131, bpm)
keypress("C", x, bpm)
rest(0.119, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.015, bpm)
keypress("n", x, bpm)
rest(0.235, bpm)
keypress("!", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("Z", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.559, bpm)
keypress("J", x, bpm)
rest(0.559, bpm)
keypress("L", x, bpm)
rest(0.559, bpm)
keypress("G", x, bpm)
rest(0.559, bpm)
keypress("H", x, bpm)
rest(0.679, bpm)
keypress("J", x, bpm)
rest(0.679, bpm)
keypress("G", x, bpm)
rest(0.679, bpm)
keypress("H", x, bpm)

finishedSong()