keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)

finishedSong()