rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)

finishedSong()