keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(3.5, bpm)
keypress("O", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(2.25, bpm)
keypress("O", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
rest(1.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(3.723, bpm)
keypress("O", x, bpm)
rest(1.79, bpm)
keypress("O", x, bpm)
rest(1.268, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
rest(1.333, bpm)
keypress("O", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
rest(1.333, bpm)
keypress("O", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
rest(0.667, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(1.346, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.897, bpm)
keypress("j", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(1.346, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("k", x, bpm)
keypress("O", x, bpm)
rest(2.691, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
rest(0.449, bpm)
keypress("a", x, bpm)
rest(0.224, bpm)
keypress("p", x, bpm)
rest(0.224, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("k", x, bpm)
keypress("O", x, bpm)
rest(4.035, bpm)
keypress("Y", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.097, bpm)
keypress("r", x, bpm)
rest(4.783, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(2.44, bpm)
keypress("G", x, bpm)
rest(2.44, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("u", x, bpm)
rest(0.407, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("I", x, bpm)
rest(0.407, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
rest(0.813, bpm)
keypress("7", x, bpm)
rest(0.1, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.103, bpm)
keypress("7", x, bpm)
rest(0.049, bpm)
keypress("7", x, bpm)
rest(0.051, bpm)
keypress("7", x, bpm)
rest(0.051, bpm)
keypress("7", x, bpm)
rest(0.051, bpm)
keypress("7", x, bpm)
rest(0.051, bpm)
keypress("7", x, bpm)
rest(0.051, bpm)
keypress("7", x, bpm)
rest(0.051, bpm)
keypress("7", x, bpm)
rest(0.051, bpm)
keypress("7", x, bpm)
rest(0.049, bpm)
keypress("7", x, bpm)
rest(0.051, bpm)
keypress("7", x, bpm)
rest(0.051, bpm)
keypress("7", x, bpm)
rest(0.054, bpm)
keypress("H", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("x", x, bpm)
keypress("b", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("3", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("3", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("Z", x, bpm)
keypress("b", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("x", x, bpm)
keypress("b", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("x", x, bpm)
keypress("b", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.407, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
rest(0.203, bpm)
keypress("Z", x, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("x", x, bpm)
rest(0.102, bpm)
keypress("x", x, bpm)
rest(0.102, bpm)
keypress("V", x, bpm)
rest(4.473, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("p", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("u", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("(", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(10.763, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("$", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("$", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("3", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("$", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("$", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("3", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("Y", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("8", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("8", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("Y", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("8", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("I", x, bpm)
keypress("8", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("8", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.203, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("^", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("^", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("^", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("^", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("^", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("^", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.203, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("*", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.175, bpm)
keypress("a", x, bpm)
rest(0.029, bpm)
keypress("*", x, bpm)
rest(0.146, bpm)
keypress("s", x, bpm)
rest(0.058, bpm)
keypress("6", x, bpm)
rest(0.117, bpm)
keypress("d", x, bpm)
rest(0.086, bpm)
keypress("*", x, bpm)
rest(0.086, bpm)
keypress("f", x, bpm)
rest(0.117, bpm)
keypress("6", x, bpm)
rest(0.058, bpm)
keypress("g", x, bpm)
rest(0.146, bpm)
keypress("*", x, bpm)
rest(0.029, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.175, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("J", x, bpm)
keypress("i", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("i", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("J", x, bpm)
keypress("i", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("i", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("J", x, bpm)
keypress("i", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("i", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("T", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("T", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("P", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("T", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("T", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("T", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("T", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("T", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("T", x, bpm)
rest(0.203, bpm)
keypress("u", x, bpm)
rest(0.203, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("Q", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("J", x, bpm)
keypress("Y", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Y", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("Q", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("J", x, bpm)
keypress("Y", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Y", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("Q", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("Q", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("h", x, bpm)
keypress("Q", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("Q", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("Q", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("Q", x, bpm)
rest(0.203, bpm)
keypress("e", x, bpm)
rest(0.203, bpm)
keypress("t", x, bpm)
rest(0.203, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("y", x, bpm)
rest(8.538, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.1, bpm)
keypress("y", x, bpm)
rest(1.12, bpm)
keypress("o", x, bpm)
rest(1.22, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(4.88, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1.22, bpm)
keypress("Y", x, bpm)
rest(1.22, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1.22, bpm)
keypress("I", x, bpm)
rest(4.811, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(3.748, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
rest(3.972, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
rest(6.1, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
keypress("0", x, bpm)
rest(4.473, bpm)
keypress("p", x, bpm)
rest(6.1, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("u", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("(", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("u", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("(", x, bpm)
rest(0.449, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
rest(0.449, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("T", x, bpm)
rest(0.075, bpm)
keypress("Y", x, bpm)

finishedSong()