keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
rest(0.2, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.2, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("s", x, bpm)
rest(1.2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
rest(0.2, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1.2, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("!", x, bpm)
rest(0.2, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
rest(0.3, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("5", x, bpm)
keypress("@", x, bpm)
rest(0.3, bpm)
keypress("5", x, bpm)
rest(0.2, bpm)
keypress("(", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
rest(0.3, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("!", x, bpm)
rest(0.2, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
rest(0.3, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("5", x, bpm)
keypress("@", x, bpm)
rest(0.3, bpm)
keypress("5", x, bpm)
rest(0.2, bpm)
keypress("(", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.2, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.3, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("@", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("7", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("^", x, bpm)
rest(0.3, bpm)
keypress("8", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("L", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("L", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("L", x, bpm)
keypress("V", x, bpm)
keypress("L", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
rest(0.3, bpm)
keypress("V", x, bpm)
rest(0.2, bpm)
keypress("v", x, bpm)
keypress("a", x, bpm)
rest(0.3, bpm)
keypress("V", x, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("x", x, bpm)
keypress("a", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("L", x, bpm)
keypress("V", x, bpm)
keypress("L", x, bpm)
keypress("a", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("a", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("a", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("V", x, bpm)
keypress("a", x, bpm)
rest(0.3, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("a", x, bpm)
rest(0.3, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
rest(0.3, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
rest(0.2, bpm)
keypress("B", x, bpm)
keypress("z", x, bpm)
rest(0.3, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
rest(0.2, bpm)
keypress("n", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("Z", x, bpm)
keypress("S", x, bpm)
rest(0.3, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("v", x, bpm)
keypress("D", x, bpm)
rest(0.3, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("Z", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("D", x, bpm)
rest(0.3, bpm)
keypress("v", x, bpm)
keypress("Z", x, bpm)
keypress("x", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("Z", x, bpm)
rest(0.2, bpm)
keypress("L", x, bpm)
keypress("D", x, bpm)
rest(0.3, bpm)
keypress("n", x, bpm)
rest(0.2, bpm)
keypress("B", x, bpm)
keypress("S", x, bpm)
rest(0.3, bpm)
keypress("V", x, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("2", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.215, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.215, bpm)
keypress("f", x, bpm)
rest(0.071, bpm)
keypress("3", x, bpm)
rest(0.144, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.212, bpm)
keypress("f", x, bpm)
rest(0.144, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.071, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.215, bpm)
keypress("f", x, bpm)
rest(0.215, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
keypress("8", x, bpm)
rest(0.3, bpm)
keypress("Z", x, bpm)
rest(0.2, bpm)
keypress("z", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3, bpm)
keypress("L", x, bpm)
rest(0.2, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.3, bpm)
keypress("j", x, bpm)
rest(0.2, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
rest(0.2, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("7", x, bpm)
rest(0.3, bpm)
keypress("k", x, bpm)
rest(0.2, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("z", x, bpm)
rest(0.2, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.3, bpm)
keypress("x", x, bpm)
rest(0.2, bpm)
keypress("b", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.3, bpm)
keypress("z", x, bpm)
rest(0.2, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("j", x, bpm)
rest(0.2, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
keypress("j", x, bpm)
rest(0.2, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.3, bpm)
keypress("p", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.3, bpm)
keypress("u", x, bpm)
rest(0.2, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.3, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.2, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.2, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.3, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("(", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("7", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(0.3, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("%", x, bpm)
rest(0.2, bpm)
keypress("^", x, bpm)
rest(0.3, bpm)
keypress("8", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
rest(0.2, bpm)
keypress("V", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.3, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("o", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("u", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
rest(0.2, bpm)
keypress("k", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("J", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.3, bpm)
keypress("J", x, bpm)
rest(0.2, bpm)
keypress("k", x, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
rest(0.3, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("k", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.3, bpm)
keypress("L", x, bpm)
rest(0.2, bpm)
keypress("Z", x, bpm)
keypress("o", x, bpm)
rest(0.3, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("Z", x, bpm)
rest(0.3, bpm)
keypress("Z", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("x", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("Z", x, bpm)
keypress("S", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
rest(0.3, bpm)
keypress("k", x, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("J", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("a", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
keypress("5", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("k", x, bpm)
rest(0.167, bpm)
keypress("L", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("V", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("v", x, bpm)
rest(0.167, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("n", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.167, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("v", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.125, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
keypress("8", x, bpm)
rest(0.123, bpm)
keypress("x", x, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.002, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.121, bpm)
keypress("x", x, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("m", x, bpm)
keypress("x", x, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.004, bpm)
keypress("3", x, bpm)
rest(0.119, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.006, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.117, bpm)
keypress("x", x, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.008, bpm)
keypress("2", x, bpm)
keypress("7", x, bpm)
rest(0.115, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
keypress("m", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.01, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.113, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
keypress("m", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
keypress("m", x, bpm)
rest(0.137, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(0.123, bpm)
keypress("x", x, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.002, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.121, bpm)
keypress("x", x, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("m", x, bpm)
keypress("x", x, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.004, bpm)
keypress("0", x, bpm)
rest(0.119, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.006, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.117, bpm)
keypress("x", x, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.008, bpm)
keypress("3", x, bpm)
rest(0.115, bpm)
keypress("m", x, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
keypress("m", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.01, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.113, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
keypress("m", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
keypress("m", x, bpm)
rest(0.137, bpm)
keypress("H", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
keypress("8", x, bpm)
rest(0.3, bpm)
keypress("Z", x, bpm)
rest(0.2, bpm)
keypress("z", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3, bpm)
keypress("L", x, bpm)
rest(0.2, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.3, bpm)
keypress("j", x, bpm)
rest(0.2, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
rest(0.2, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("7", x, bpm)
rest(0.3, bpm)
keypress("k", x, bpm)
rest(0.2, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("z", x, bpm)
rest(0.2, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.3, bpm)
keypress("x", x, bpm)
rest(0.2, bpm)
keypress("b", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.3, bpm)
keypress("z", x, bpm)
rest(0.2, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("j", x, bpm)
rest(0.2, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
keypress("j", x, bpm)
rest(0.2, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.3, bpm)
keypress("p", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.3, bpm)
keypress("u", x, bpm)
rest(0.2, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.3, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.2, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("b", x, bpm)

finishedSong()