keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.667, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)

finishedSong()