keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.11, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.11, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.11, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.36, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.11, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.36, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(2.5, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(2.5, bpm)
keypress("T", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
rest(0.019, bpm)
keypress("Y", x, bpm)
rest(0.021, bpm)
keypress("y", x, bpm)
rest(0.023, bpm)
keypress("T", x, bpm)
rest(0.019, bpm)
keypress("t", x, bpm)
rest(0.021, bpm)
keypress("r", x, bpm)
rest(0.023, bpm)
keypress("E", x, bpm)
rest(0.019, bpm)
keypress("e", x, bpm)
rest(0.021, bpm)
keypress("W", x, bpm)
rest(0.023, bpm)
keypress("w", x, bpm)
rest(0.019, bpm)
keypress("Q", x, bpm)
rest(0.021, bpm)
keypress("q", x, bpm)
rest(0.023, bpm)
keypress("0", x, bpm)
rest(0.019, bpm)
keypress("(", x, bpm)
rest(0.021, bpm)
keypress("9", x, bpm)
rest(0.023, bpm)
keypress("*", x, bpm)
rest(0.019, bpm)
keypress("8", x, bpm)
rest(0.021, bpm)
keypress("7", x, bpm)
rest(0.023, bpm)
keypress("^", x, bpm)
rest(0.019, bpm)
keypress("6", x, bpm)
rest(0.021, bpm)
keypress("%", x, bpm)
rest(0.023, bpm)
keypress("5", x, bpm)
rest(0.019, bpm)
keypress("$", x, bpm)
rest(0.044, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.36, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.11, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.11, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.11, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.36, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.11, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.14, bpm)
keypress("i", x, bpm)
rest(0.36, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(2.5, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(2.5, bpm)
keypress("T", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
rest(0.019, bpm)
keypress("Y", x, bpm)
rest(0.021, bpm)
keypress("y", x, bpm)
rest(0.023, bpm)
keypress("T", x, bpm)
rest(0.019, bpm)
keypress("t", x, bpm)
rest(0.021, bpm)
keypress("r", x, bpm)
rest(0.023, bpm)
keypress("E", x, bpm)
rest(0.019, bpm)
keypress("e", x, bpm)
rest(0.021, bpm)
keypress("W", x, bpm)
rest(0.023, bpm)
keypress("w", x, bpm)
rest(0.019, bpm)
keypress("Q", x, bpm)
rest(0.021, bpm)
keypress("q", x, bpm)
rest(0.023, bpm)
keypress("0", x, bpm)
rest(0.019, bpm)
keypress("(", x, bpm)
rest(0.021, bpm)
keypress("9", x, bpm)
rest(0.023, bpm)
keypress("*", x, bpm)
rest(0.019, bpm)
keypress("8", x, bpm)
rest(0.021, bpm)
keypress("7", x, bpm)
rest(0.023, bpm)
keypress("^", x, bpm)
rest(0.019, bpm)
keypress("6", x, bpm)
rest(0.021, bpm)
keypress("%", x, bpm)
rest(0.023, bpm)
keypress("5", x, bpm)
rest(0.019, bpm)
keypress("$", x, bpm)
rest(0.044, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)

finishedSong()