keypress("c", x, bpm)
keypress("G", x, bpm)
rest(0.106, bpm)
keypress("H", x, bpm)
rest(0.115, bpm)
keypress("L", x, bpm)
rest(0.279, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("B", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("B", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("G", x, bpm)
rest(0.106, bpm)
keypress("J", x, bpm)
rest(0.115, bpm)
keypress("l", x, bpm)
rest(0.279, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("g", x, bpm)
rest(0.106, bpm)
keypress("H", x, bpm)
rest(0.115, bpm)
keypress("l", x, bpm)
rest(0.279, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("P", x, bpm)
rest(0.11, bpm)
keypress("g", x, bpm)
rest(0.11, bpm)
keypress("H", x, bpm)
rest(0.279, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("O", x, bpm)
rest(0.11, bpm)
keypress("s", x, bpm)
rest(0.11, bpm)
keypress("S", x, bpm)
rest(0.117, bpm)
keypress("g", x, bpm)
rest(0.163, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("G", x, bpm)
rest(0.106, bpm)
keypress("H", x, bpm)
rest(0.115, bpm)
keypress("L", x, bpm)
rest(0.279, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("B", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("B", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("G", x, bpm)
rest(0.106, bpm)
keypress("J", x, bpm)
rest(0.115, bpm)
keypress("l", x, bpm)
rest(0.279, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("g", x, bpm)
rest(0.106, bpm)
keypress("H", x, bpm)
rest(0.115, bpm)
keypress("l", x, bpm)
rest(0.279, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("P", x, bpm)
rest(0.106, bpm)
keypress("g", x, bpm)
rest(0.115, bpm)
keypress("H", x, bpm)
rest(0.279, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("I", x, bpm)
rest(0.106, bpm)
keypress("O", x, bpm)
rest(0.115, bpm)
keypress("S", x, bpm)
rest(0.115, bpm)
keypress("g", x, bpm)
rest(0.165, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("I", x, bpm)
rest(0.106, bpm)
keypress("P", x, bpm)
rest(0.115, bpm)
keypress("s", x, bpm)
rest(0.115, bpm)
keypress("g", x, bpm)
rest(0.165, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("i", x, bpm)
rest(0.106, bpm)
keypress("O", x, bpm)
rest(0.115, bpm)
keypress("s", x, bpm)
rest(0.115, bpm)
keypress("S", x, bpm)
rest(0.165, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("P", x, bpm)
rest(0.11, bpm)
keypress("s", x, bpm)
rest(0.11, bpm)
keypress("S", x, bpm)
rest(0.117, bpm)
keypress("g", x, bpm)
rest(0.162, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("O", x, bpm)
rest(0.11, bpm)
keypress("s", x, bpm)
rest(0.11, bpm)
keypress("S", x, bpm)
rest(0.117, bpm)
keypress("g", x, bpm)
rest(0.162, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("I", x, bpm)
rest(0.106, bpm)
keypress("O", x, bpm)
rest(0.115, bpm)
keypress("S", x, bpm)
rest(0.115, bpm)
keypress("g", x, bpm)
rest(0.165, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("I", x, bpm)
rest(0.106, bpm)
keypress("P", x, bpm)
rest(0.115, bpm)
keypress("s", x, bpm)
rest(0.115, bpm)
keypress("g", x, bpm)
rest(0.165, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("i", x, bpm)
rest(0.106, bpm)
keypress("O", x, bpm)
rest(0.115, bpm)
keypress("s", x, bpm)
rest(0.115, bpm)
keypress("S", x, bpm)
rest(0.165, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("P", x, bpm)
rest(0.106, bpm)
keypress("s", x, bpm)
rest(0.115, bpm)
keypress("S", x, bpm)
rest(0.115, bpm)
keypress("g", x, bpm)
rest(0.165, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(2.684, bpm)
keypress("%", x, bpm)
keypress("Q", x, bpm)
rest(1.342, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(2.684, bpm)
keypress("^", x, bpm)
rest(1.342, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(1.342, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(1.342, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(2.684, bpm)
keypress("%", x, bpm)
keypress("Q", x, bpm)
rest(1.342, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(2.684, bpm)
keypress("^", x, bpm)
rest(2.684, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(2.684, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(2.684, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(1.342, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(2.684, bpm)
keypress("^", x, bpm)
rest(1.342, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.112, bpm)
keypress("g", x, bpm)
rest(0.112, bpm)
keypress("L", x, bpm)
rest(1.118, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("H", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(1.342, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(2.684, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(1.342, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
rest(4.026, bpm)
keypress("E", x, bpm)
rest(1.342, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(1.342, bpm)
keypress("T", x, bpm)
rest(1.342, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(1.342, bpm)
keypress("P", x, bpm)
rest(1.342, bpm)
keypress("E", x, bpm)
keypress("%", x, bpm)
rest(0.056, bpm)
keypress("r", x, bpm)
rest(0.056, bpm)
keypress("Y", x, bpm)
rest(0.056, bpm)
keypress("I", x, bpm)
rest(0.056, bpm)
keypress("P", x, bpm)
rest(0.447, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(1.342, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("I", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(1.342, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1.342, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
rest(1.342, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(2.013, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(1.342, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1.342, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.056, bpm)
keypress("Y", x, bpm)
rest(0.056, bpm)
keypress("I", x, bpm)
rest(0.056, bpm)
keypress("P", x, bpm)
rest(0.503, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(1.342, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("I", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
rest(1.342, bpm)
keypress("i", x, bpm)
rest(1.342, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(3.355, bpm)
keypress("Z", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("c", x, bpm)
rest(0.671, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
rest(0.671, bpm)
keypress("Z", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(2.684, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(1.342, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
rest(0.671, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.671, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(2.684, bpm)
keypress("^", x, bpm)
rest(1.342, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.112, bpm)
keypress("c", x, bpm)
rest(0.112, bpm)
keypress("L", x, bpm)
rest(1.118, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("m", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("V", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(1.342, bpm)
keypress("Z", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("c", x, bpm)
rest(0.671, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
rest(0.671, bpm)
keypress("Z", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(2.684, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(1.342, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
rest(0.671, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(2.684, bpm)
keypress("Z", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
rest(0.671, bpm)
keypress("L", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.109, bpm)
keypress("8", x, bpm)
rest(0.115, bpm)
keypress("q", x, bpm)
rest(0.447, bpm)
keypress("s", x, bpm)
rest(0.671, bpm)
keypress("S", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(2.684, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(1.342, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(2.684, bpm)
keypress("^", x, bpm)
rest(1.342, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.112, bpm)
keypress("g", x, bpm)
rest(0.112, bpm)
keypress("L", x, bpm)
rest(1.118, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("H", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
rest(1.342, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1.342, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1.342, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1.342, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.671, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.342, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("S", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(1.342, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1.342, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.336, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
rest(0.336, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("t", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("m", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("V", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.109, bpm)
keypress("H", x, bpm)
rest(0.109, bpm)
keypress("Z", x, bpm)
rest(0.453, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("Q", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.671, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.671, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("5", x, bpm)
rest(0.671, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.671, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.671, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.671, bpm)
keypress("^", x, bpm)
rest(0.671, bpm)
keypress("w", x, bpm)
rest(0.671, bpm)
keypress("S", x, bpm)
rest(0.671, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.671, bpm)
keypress("(", x, bpm)
rest(0.671, bpm)
keypress("W", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.671, bpm)
keypress("%", x, bpm)
rest(0.671, bpm)
keypress("i", x, bpm)
rest(0.671, bpm)
keypress("Y", x, bpm)
rest(0.671, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.022, bpm)
keypress("E", x, bpm)
rest(0.143, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.21, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
rest(0.109, bpm)
keypress("r", x, bpm)
rest(0.056, bpm)
keypress("$", x, bpm)
rest(0.053, bpm)
keypress("t", x, bpm)
rest(0.115, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.022, bpm)
keypress("Y", x, bpm)
rest(0.109, bpm)
keypress("T", x, bpm)
rest(0.034, bpm)
keypress("$", x, bpm)
rest(0.075, bpm)
keypress("y", x, bpm)
rest(0.092, bpm)
keypress("$", x, bpm)
rest(0.02, bpm)
keypress("t", x, bpm)
rest(0.145, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.034, bpm)
keypress("q", x, bpm)
rest(0.134, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.21, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
rest(0.109, bpm)
keypress("P", x, bpm)
rest(0.056, bpm)
keypress("$", x, bpm)
rest(0.059, bpm)
keypress("g", x, bpm)
rest(0.109, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.022, bpm)
keypress("i", x, bpm)
rest(0.143, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.21, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.109, bpm)
keypress("a", x, bpm)
rest(0.056, bpm)
keypress("$", x, bpm)
rest(0.053, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.115, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.022, bpm)
keypress("D", x, bpm)
rest(0.109, bpm)
keypress("d", x, bpm)
rest(0.034, bpm)
keypress("$", x, bpm)
rest(0.075, bpm)
keypress("S", x, bpm)
rest(0.092, bpm)
keypress("$", x, bpm)
rest(0.02, bpm)
keypress("s", x, bpm)
rest(0.145, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.034, bpm)
keypress("i", x, bpm)
rest(0.134, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.21, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
rest(0.109, bpm)
keypress("J", x, bpm)
rest(0.056, bpm)
keypress("$", x, bpm)
rest(0.059, bpm)
keypress("c", x, bpm)
rest(0.109, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.022, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.143, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.21, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.109, bpm)
keypress("k", x, bpm)
rest(0.056, bpm)
keypress("$", x, bpm)
rest(0.053, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
rest(0.115, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.022, bpm)
keypress("Z", x, bpm)
rest(0.109, bpm)
keypress("z", x, bpm)
rest(0.034, bpm)
keypress("$", x, bpm)
rest(0.075, bpm)
keypress("L", x, bpm)
rest(0.092, bpm)
keypress("$", x, bpm)
rest(0.02, bpm)
keypress("l", x, bpm)
rest(0.145, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.034, bpm)
keypress("g", x, bpm)
rest(0.134, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.21, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.022, bpm)
keypress("g", x, bpm)
rest(0.143, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.21, bpm)
keypress("J", x, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.022, bpm)
keypress("g", x, bpm)
rest(0.143, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.165, bpm)
keypress("$", x, bpm)
rest(0.168, bpm)
keypress("$", x, bpm)
rest(0.21, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
rest(0.106, bpm)
keypress("J", x, bpm)
rest(0.112, bpm)
keypress("l", x, bpm)
rest(0.117, bpm)
keypress("c", x, bpm)

finishedSong()