keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("s", x, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("r", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("h", x, bpm)
rest(0.315, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.315, bpm)
keypress("l", x, bpm)
rest(0.315, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("s", x, bpm)
rest(0.63, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("p", x, bpm)
rest(0.315, bpm)
keypress("p", x, bpm)
rest(0.315, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("s", x, bpm)
rest(0.315, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("s", x, bpm)
rest(0.63, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("p", x, bpm)
rest(0.315, bpm)
keypress("p", x, bpm)
rest(0.315, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("f", x, bpm)
rest(0.157, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.315, bpm)
keypress("p", x, bpm)
rest(0.315, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("s", x, bpm)
rest(0.315, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.315, bpm)
keypress("p", x, bpm)
rest(0.315, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("f", x, bpm)
rest(0.157, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.315, bpm)
keypress("p", x, bpm)
rest(0.315, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("s", x, bpm)
rest(0.315, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.315, bpm)
keypress("p", x, bpm)
rest(0.315, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("f", x, bpm)
rest(0.157, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("p", x, bpm)
rest(0.157, bpm)
keypress("o", x, bpm)
rest(0.472, bpm)
keypress("d", x, bpm)
rest(0.157, bpm)
keypress("a", x, bpm)
rest(0.472, bpm)
keypress("h", x, bpm)
rest(0.157, bpm)
keypress("f", x, bpm)
rest(0.472, bpm)
keypress("l", x, bpm)
rest(0.157, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("x", x, bpm)
rest(1.259, bpm)
keypress("v", x, bpm)
rest(0.472, bpm)
keypress("x", x, bpm)
rest(0.157, bpm)
keypress("l", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("z", x, bpm)
rest(0.157, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("f", x, bpm)
rest(0.157, bpm)
keypress("y", x, bpm)
rest(0.63, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.63, bpm)
keypress("y", x, bpm)
rest(0.63, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.63, bpm)
keypress("y", x, bpm)
rest(0.63, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.63, bpm)
keypress("y", x, bpm)
rest(0.63, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.63, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.472, bpm)
keypress("d", x, bpm)
rest(0.157, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("d", x, bpm)
rest(0.157, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.63, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("g", x, bpm)
rest(0.157, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.472, bpm)
keypress("s", x, bpm)
rest(0.157, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.472, bpm)
keypress("d", x, bpm)
rest(0.157, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("d", x, bpm)
rest(0.157, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.63, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("g", x, bpm)
rest(0.157, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("q", x, bpm)
rest(0.63, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("p", x, bpm)
rest(0.157, bpm)
keypress("o", x, bpm)
rest(0.472, bpm)
keypress("d", x, bpm)
rest(0.157, bpm)
keypress("a", x, bpm)
rest(0.472, bpm)
keypress("h", x, bpm)
rest(0.157, bpm)
keypress("f", x, bpm)
rest(0.472, bpm)
keypress("l", x, bpm)
rest(0.157, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("x", x, bpm)
rest(1.259, bpm)
keypress("v", x, bpm)
rest(0.472, bpm)
keypress("x", x, bpm)
rest(0.157, bpm)
keypress("l", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("z", x, bpm)
rest(0.157, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("f", x, bpm)
rest(0.157, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("p", x, bpm)
rest(0.157, bpm)
keypress("o", x, bpm)
rest(0.472, bpm)
keypress("d", x, bpm)
rest(0.157, bpm)
keypress("a", x, bpm)
rest(0.472, bpm)
keypress("h", x, bpm)
rest(0.157, bpm)
keypress("f", x, bpm)
rest(0.472, bpm)
keypress("l", x, bpm)
rest(0.157, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("x", x, bpm)
rest(1.259, bpm)
keypress("v", x, bpm)
rest(0.472, bpm)
keypress("x", x, bpm)
rest(0.157, bpm)
keypress("l", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.472, bpm)
keypress("z", x, bpm)
rest(0.157, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
rest(0.315, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
rest(0.315, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.472, bpm)
keypress("f", x, bpm)
rest(0.157, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.63, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
rest(0.63, bpm)
keypress("y", x, bpm)
rest(0.63, bpm)
keypress("r", x, bpm)
rest(0.63, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("9", x, bpm)
rest(0.63, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.63, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.63, bpm)
keypress("i", x, bpm)
rest(0.63, bpm)
keypress("y", x, bpm)
rest(0.63, bpm)
keypress("r", x, bpm)
rest(0.63, bpm)
keypress("t", x, bpm)
rest(0.63, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)

finishedSong()