keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.503, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.091, bpm)
keypress("k", x, bpm)
rest(0.411, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.503, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.503, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.089, bpm)
keypress("z", x, bpm)
rest(0.414, bpm)
keypress("z", x, bpm)
keypress("r", x, bpm)
rest(2.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.503, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.089, bpm)
keypress("z", x, bpm)
rest(0.414, bpm)
keypress("z", x, bpm)
keypress("r", x, bpm)
rest(2.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.089, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(2.411, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.089, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2.914, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.089, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1.414, bpm)
keypress("g", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.089, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.414, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(1.5, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("r", x, bpm)
rest(1.003, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.503, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.091, bpm)
keypress("k", x, bpm)
rest(0.411, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.503, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.503, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.089, bpm)
keypress("z", x, bpm)
rest(0.414, bpm)
keypress("z", x, bpm)
keypress("r", x, bpm)
rest(2.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(2.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.503, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.089, bpm)
keypress("z", x, bpm)
rest(0.414, bpm)
keypress("z", x, bpm)
keypress("r", x, bpm)
rest(2.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.089, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(2.411, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.089, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2.914, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.089, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1.414, bpm)
keypress("g", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.089, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.414, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(1.5, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("r", x, bpm)
rest(1.003, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)

finishedSong()