keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.503, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.503, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.177, bpm)
keypress("g", x, bpm)
rest(1.323, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.323, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.497, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.177, bpm)
keypress("g", x, bpm)
rest(1.323, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.323, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.497, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.503, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.503, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.503, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.503, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.177, bpm)
keypress("g", x, bpm)
rest(1.323, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.323, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.497, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.177, bpm)
keypress("g", x, bpm)
rest(1.323, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.323, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.497, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.503, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.177, bpm)
keypress("h", x, bpm)
rest(0.823, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.503, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)

finishedSong()