keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
rest(0.375, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
rest(0.375, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
rest(0.375, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
rest(0.375, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.336, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.336, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.336, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.336, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.336, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.336, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
rest(0.336, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
rest(0.336, bpm)
keypress("c", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
rest(0.336, bpm)
keypress("z", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
rest(0.336, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
rest(0.336, bpm)
keypress("c", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
rest(0.336, bpm)
keypress("z", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.336, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.336, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.336, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.336, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.336, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.336, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
rest(0.336, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("l", x, bpm)
rest(0.336, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
rest(0.336, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("c", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
rest(0.336, bpm)
keypress("v", x, bpm)
rest(0.333, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("V", x, bpm)
rest(0.336, bpm)
keypress("v", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("c", x, bpm)
rest(0.336, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.169, bpm)
keypress("r", x, bpm)
rest(0.169, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.169, bpm)
keypress("t", x, bpm)
rest(0.169, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
rest(0.375, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
rest(0.375, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
rest(0.375, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
rest(0.375, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.336, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.336, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.336, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.336, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.336, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.336, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
rest(0.336, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
rest(0.336, bpm)
keypress("c", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
rest(0.336, bpm)
keypress("z", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
rest(0.336, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
rest(0.336, bpm)
keypress("c", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
rest(0.336, bpm)
keypress("z", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.336, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.336, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.336, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.336, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.336, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.336, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.336, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
rest(0.336, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("l", x, bpm)
rest(0.336, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
rest(0.336, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("c", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
rest(0.336, bpm)
keypress("v", x, bpm)
rest(0.333, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("V", x, bpm)
rest(0.336, bpm)
keypress("v", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("c", x, bpm)
rest(0.336, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.169, bpm)
keypress("r", x, bpm)
rest(0.169, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.169, bpm)
keypress("t", x, bpm)
rest(0.169, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)

finishedSong()