keypress("y", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("b", x, bpm)
rest(1, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("b", x, bpm)
rest(1, bpm)
keypress("x", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(4, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(1.125, bpm)
keypress("b", x, bpm)
rest(1, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("b", x, bpm)
rest(1, bpm)
keypress("m", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("b", x, bpm)
rest(6, bpm)
keypress("D8", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)

finishedSong()