keypress("1", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("m", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("1", x, bpm)
rest(0.154, bpm)
keypress("v", x, bpm)
rest(0.846, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("m", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("m", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(2.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(3, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(2.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(3, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(3, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("m", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("m", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("m", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("1", x, bpm)
rest(0.154, bpm)
keypress("v", x, bpm)
rest(0.846, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("m", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("1", x, bpm)
rest(0.154, bpm)
keypress("v", x, bpm)
rest(0.846, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("m", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)

finishedSong()