keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(2.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("B", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(2, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.667, bpm)
keypress("k", x, bpm)
rest(0.667, bpm)
keypress("L", x, bpm)
rest(0.667, bpm)
keypress("z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.285, bpm)
keypress("Z", x, bpm)
rest(0.285, bpm)
keypress("c", x, bpm)
rest(0.285, bpm)
keypress("C", x, bpm)
rest(0.288, bpm)
keypress("v", x, bpm)
rest(0.285, bpm)
keypress("V", x, bpm)
rest(0.285, bpm)
keypress("b", x, bpm)
rest(0.285, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.017, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("(", x, bpm)
rest(0.106, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.123, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("B", x, bpm)
rest(0.025, bpm)
keypress("q", x, bpm)
rest(0.1, bpm)
keypress("J", x, bpm)
rest(0.123, bpm)
keypress("B", x, bpm)
rest(0.125, bpm)
keypress("J", x, bpm)
rest(0.123, bpm)
keypress("B", x, bpm)
rest(0.029, bpm)
keypress("Q", x, bpm)
rest(0.096, bpm)
keypress("J", x, bpm)
rest(0.123, bpm)
keypress("B", x, bpm)
rest(0.125, bpm)
keypress("J", x, bpm)
rest(0.156, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(1.011, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1.022, bpm)
keypress("G", x, bpm)
rest(1.034, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1.045, bpm)
keypress("G", x, bpm)
rest(1.057, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1.611, bpm)
keypress("D", x, bpm)
rest(0.541, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.095, bpm)
keypress("S", x, bpm)
rest(1.108, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.121, bpm)
keypress("g", x, bpm)
rest(0.024, bpm)
keypress("H", x, bpm)
rest(0.026, bpm)
keypress("J", x, bpm)
rest(0.028, bpm)
keypress("L", x, bpm)

finishedSong()