keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)

finishedSong()