keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("o", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
rest(0.167, bpm)
keypress("w", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("o", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
rest(0.167, bpm)
keypress("w", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("o", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
rest(0.167, bpm)
keypress("w", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("o", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
rest(0.167, bpm)
keypress("w", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
rest(0.167, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("w", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.083, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(1.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(1.75, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("2", x, bpm)
rest(1.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.49, bpm)
keypress("t", x, bpm)
rest(0.49, bpm)
keypress("t", x, bpm)
rest(0.48, bpm)
keypress("t", x, bpm)
rest(0.48, bpm)
keypress("t", x, bpm)
rest(0.471, bpm)
keypress("t", x, bpm)
rest(0.471, bpm)
keypress("t", x, bpm)
rest(0.462, bpm)
keypress("t", x, bpm)
rest(0.462, bpm)
keypress("t", x, bpm)
rest(0.453, bpm)
keypress("t", x, bpm)
rest(0.453, bpm)
keypress("t", x, bpm)
rest(0.445, bpm)
keypress("t", x, bpm)
rest(0.445, bpm)
keypress("t", x, bpm)
rest(0.437, bpm)
keypress("t", x, bpm)
rest(0.437, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.429, bpm)
keypress("t", x, bpm)
rest(0.429, bpm)
keypress("t", x, bpm)
rest(0.422, bpm)
keypress("t", x, bpm)
rest(0.422, bpm)
keypress("t", x, bpm)
rest(0.415, bpm)
keypress("t", x, bpm)
rest(0.415, bpm)
keypress("t", x, bpm)
rest(0.408, bpm)
keypress("t", x, bpm)
rest(0.408, bpm)
keypress("t", x, bpm)
rest(0.401, bpm)
keypress("t", x, bpm)
rest(0.401, bpm)
keypress("t", x, bpm)
rest(0.394, bpm)
keypress("t", x, bpm)
rest(0.394, bpm)
keypress("t", x, bpm)
rest(0.388, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.388, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.382, bpm)
keypress("t", x, bpm)
rest(0.382, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.206, bpm)
keypress("D", x, bpm)
rest(0.206, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.075, bpm)
keypress("s", x, bpm)
rest(0.079, bpm)
keypress("D", x, bpm)
rest(0.077, bpm)
keypress("h", x, bpm)
rest(0.18, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.412, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.412, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.075, bpm)
keypress("s", x, bpm)
rest(0.079, bpm)
keypress("D", x, bpm)
rest(0.077, bpm)
keypress("h", x, bpm)
rest(0.18, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.206, bpm)
keypress("D", x, bpm)
rest(0.206, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.075, bpm)
keypress("s", x, bpm)
rest(0.079, bpm)
keypress("D", x, bpm)
rest(0.077, bpm)
keypress("h", x, bpm)
rest(0.18, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.412, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.412, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.412, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.206, bpm)
keypress("d", x, bpm)
rest(0.206, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.206, bpm)
keypress("d", x, bpm)
rest(0.206, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.206, bpm)
keypress("d", x, bpm)
rest(0.206, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("O", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.412, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(3.889, bpm)
keypress("^", x, bpm)
rest(2.593, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.324, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.324, bpm)
keypress("g", x, bpm)
rest(0.324, bpm)
keypress("D", x, bpm)
rest(0.324, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.243, bpm)
keypress("o", x, bpm)
keypress("g", x, bpm)
rest(0.729, bpm)
keypress("o", x, bpm)
keypress("g", x, bpm)
rest(0.729, bpm)
keypress("D", x, bpm)
rest(0.122, bpm)
keypress("g", x, bpm)
rest(0.122, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(1.944, bpm)
keypress("5", x, bpm)
rest(2.593, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.324, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.324, bpm)
keypress("g", x, bpm)
rest(0.324, bpm)
keypress("D", x, bpm)
rest(0.324, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(2.431, bpm)
keypress("O", x, bpm)
keypress("h", x, bpm)
rest(0.486, bpm)
keypress("O", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.729, bpm)
keypress("D", x, bpm)
rest(0.122, bpm)
keypress("d", x, bpm)
rest(0.122, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(2.431, bpm)
keypress("h", x, bpm)
rest(0.486, bpm)
keypress("g", x, bpm)
rest(0.486, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
rest(0.243, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
rest(0.243, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1.944, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.486, bpm)
keypress("o", x, bpm)
rest(0.075, bpm)
keypress("P", x, bpm)
rest(0.079, bpm)
keypress("g", x, bpm)
rest(1.304, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1.944, bpm)
keypress("@", x, bpm)
rest(0.486, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.486, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.729, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(0.243, bpm)
keypress("%", x, bpm)
rest(0.486, bpm)
keypress("8", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
rest(0.486, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("s", x, bpm)
rest(0.243, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
rest(0.051, bpm)
keypress("s", x, bpm)
rest(0.051, bpm)
keypress("h", x, bpm)
rest(0.223, bpm)
keypress("g", x, bpm)
rest(0.162, bpm)
keypress("t", x, bpm)
rest(0.162, bpm)
keypress("D", x, bpm)
rest(0.324, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.365, bpm)
keypress("s", x, bpm)
rest(0.122, bpm)
keypress("(", x, bpm)
rest(0.486, bpm)
keypress("^", x, bpm)
rest(0.486, bpm)
keypress("9", x, bpm)
rest(0.486, bpm)
keypress("q", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("h", x, bpm)
rest(0.122, bpm)
keypress("h", x, bpm)
rest(0.122, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
rest(0.324, bpm)
keypress("g", x, bpm)
rest(0.162, bpm)
keypress("y", x, bpm)
rest(0.162, bpm)
keypress("D", x, bpm)
rest(0.324, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("q", x, bpm)
rest(0.486, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.486, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("5", x, bpm)
rest(0.486, bpm)
keypress("9", x, bpm)
rest(0.486, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.243, bpm)
keypress("s", x, bpm)
rest(0.243, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.324, bpm)
keypress("g", x, bpm)
rest(0.162, bpm)
keypress("5", x, bpm)
rest(0.162, bpm)
keypress("D", x, bpm)
rest(0.324, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
rest(0.486, bpm)
keypress("W", x, bpm)
rest(0.486, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
rest(0.486, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.486, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.486, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.486, bpm)
keypress("q", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("i", x, bpm)
rest(0.486, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.243, bpm)
keypress("D", x, bpm)
rest(0.243, bpm)
keypress("o", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("D", x, bpm)
rest(0.122, bpm)
keypress("g", x, bpm)
rest(0.122, bpm)
keypress("D", x, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
rest(0.324, bpm)
keypress("s", x, bpm)
rest(0.162, bpm)
keypress("(", x, bpm)
rest(0.162, bpm)
keypress("D", x, bpm)
rest(0.324, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.486, bpm)
keypress("9", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.486, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.243, bpm)
keypress("D", x, bpm)
rest(0.243, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
rest(0.486, bpm)
keypress("W", x, bpm)
rest(0.486, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.486, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("W", x, bpm)
rest(0.324, bpm)
keypress("s", x, bpm)
rest(0.162, bpm)
keypress("(", x, bpm)
rest(0.162, bpm)
keypress("D", x, bpm)
rest(0.324, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.486, bpm)
keypress("q", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.486, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(0.243, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.243, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.243, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.243, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.077, bpm)
keypress("D", x, bpm)
rest(0.077, bpm)
keypress("l", x, bpm)
rest(0.332, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("y", x, bpm)
rest(0.324, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.162, bpm)
keypress("E", x, bpm)
rest(0.162, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.324, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
rest(0.324, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.162, bpm)
keypress("(", x, bpm)
rest(0.162, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.324, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("5", x, bpm)
rest(0.243, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
rest(0.243, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("9", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
rest(0.243, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("9", x, bpm)
rest(0.486, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("5", x, bpm)
rest(0.243, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
rest(0.243, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.486, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.486, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.486, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.486, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.486, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.243, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.243, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.486, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.243, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.243, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.486, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.486, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.243, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.243, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("5", x, bpm)
rest(0.972, bpm)
keypress("^", x, bpm)
rest(0.486, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.486, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
rest(0.486, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.243, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.486, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.324, bpm)
keypress("i", x, bpm)
rest(0.162, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.162, bpm)
keypress("Y", x, bpm)
rest(0.324, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.486, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.486, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.486, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.243, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.243, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.486, bpm)
keypress("o", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.324, bpm)
keypress("i", x, bpm)
rest(0.162, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.162, bpm)
keypress("Y", x, bpm)
rest(0.324, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.486, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.486, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.486, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.486, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.486, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)

finishedSong()