keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
keypress("0", x, bpm)
rest(0.485, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.485, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("e", x, bpm)
rest(0.323, bpm)
keypress("q", x, bpm)
rest(0.323, bpm)
keypress("9", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("4", x, bpm)
rest(0.323, bpm)
keypress("2", x, bpm)
rest(0.323, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.485, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
rest(0.485, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.485, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.485, bpm)
keypress("4", x, bpm)
keypress("1", x, bpm)
keypress("4", x, bpm)
rest(1.455, bpm)
keypress("t", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("P", x, bpm)
keypress("e", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.485, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
keypress("0", x, bpm)
rest(0.485, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.485, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("e", x, bpm)
rest(0.323, bpm)
keypress("q", x, bpm)
rest(0.323, bpm)
keypress("9", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("4", x, bpm)
rest(0.323, bpm)
keypress("2", x, bpm)
rest(0.323, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.485, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("5", x, bpm)
rest(0.485, bpm)
keypress("w", x, bpm)
rest(0.485, bpm)
keypress("5", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.485, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.97, bpm)
keypress("e", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("0", x, bpm)
rest(0.323, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.323, bpm)
keypress("0", x, bpm)
rest(0.323, bpm)
keypress("T", x, bpm)
rest(0.323, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.323, bpm)
keypress("e", x, bpm)
rest(0.323, bpm)
keypress("0", x, bpm)
rest(0.323, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("3", x, bpm)
rest(0.323, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("3", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("0", x, bpm)
rest(0.323, bpm)
keypress("e", x, bpm)
rest(0.323, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("2", x, bpm)
rest(0.162, bpm)
keypress("2", x, bpm)
rest(0.162, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.914, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.114, bpm)
keypress("d", x, bpm)
rest(0.114, bpm)
keypress("s", x, bpm)
rest(0.229, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.114, bpm)
keypress("4", x, bpm)
rest(0.114, bpm)
keypress("4", x, bpm)
rest(0.076, bpm)
keypress("o", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("4", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.914, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("E", x, bpm)
rest(0.305, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("2", x, bpm)
rest(0.305, bpm)
keypress("2", x, bpm)
rest(0.305, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.114, bpm)
keypress("i", x, bpm)
rest(0.114, bpm)
keypress("y", x, bpm)
rest(0.686, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.305, bpm)
keypress("4", x, bpm)
rest(0.152, bpm)
keypress("f", x, bpm)
rest(0.114, bpm)
keypress("d", x, bpm)
rest(0.038, bpm)
keypress("4", x, bpm)
rest(0.076, bpm)
keypress("s", x, bpm)
rest(0.229, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.914, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("e", x, bpm)
rest(0.305, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.152, bpm)
keypress("g", x, bpm)
rest(0.152, bpm)
keypress("1", x, bpm)
rest(0.305, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("g", x, bpm)
rest(0.305, bpm)
keypress("s", x, bpm)
rest(0.305, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
rest(0.305, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("s", x, bpm)
rest(0.305, bpm)
keypress("g", x, bpm)
rest(0.305, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.914, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("E", x, bpm)
rest(0.305, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("2", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.914, bpm)
keypress("2", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.152, bpm)
keypress("y", x, bpm)
rest(0.08, bpm)
keypress("i", x, bpm)
rest(0.08, bpm)
keypress("p", x, bpm)
rest(0.08, bpm)
keypress("d", x, bpm)
rest(0.217, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.152, bpm)
keypress("f", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.305, bpm)
keypress("4", x, bpm)
rest(0.152, bpm)
keypress("f", x, bpm)
rest(0.114, bpm)
keypress("d", x, bpm)
rest(0.038, bpm)
keypress("4", x, bpm)
rest(0.076, bpm)
keypress("s", x, bpm)
rest(0.229, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.305, bpm)
keypress("o", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.61, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("4", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.914, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("E", x, bpm)
rest(0.305, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("2", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.914, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("9", x, bpm)
rest(0.152, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.152, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.305, bpm)
keypress("4", x, bpm)
rest(0.152, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.152, bpm)
keypress("4", x, bpm)
rest(0.305, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.457, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.457, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.457, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.229, bpm)
keypress("5", x, bpm)
rest(0.229, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(1.829, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(0.305, bpm)
keypress("E", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("^", x, bpm)
rest(0.152, bpm)
keypress("i", x, bpm)
rest(0.152, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.471, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.471, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("e", x, bpm)
rest(0.314, bpm)
keypress("q", x, bpm)
rest(0.314, bpm)
keypress("9", x, bpm)
rest(0.314, bpm)
keypress("6", x, bpm)
rest(0.314, bpm)
keypress("4", x, bpm)
rest(0.314, bpm)
keypress("2", x, bpm)
rest(0.314, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.471, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.157, bpm)
keypress("i", x, bpm)
rest(0.157, bpm)
keypress("P", x, bpm)
rest(0.157, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.235, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.235, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.471, bpm)
keypress("5", x, bpm)
rest(0.471, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.235, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.235, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.471, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("6", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("6", x, bpm)
rest(0.471, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.235, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.235, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.471, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("8", x, bpm)
rest(0.471, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("e", x, bpm)
rest(0.471, bpm)
keypress("8", x, bpm)
rest(0.471, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("4", x, bpm)
rest(0.235, bpm)
keypress("2", x, bpm)
rest(0.235, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("E", x, bpm)
rest(0.471, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.471, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
rest(0.471, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.471, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.471, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("5", x, bpm)
rest(0.471, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(0.471, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.471, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.314, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.314, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.314, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.314, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(0.314, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.314, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.471, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.471, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.235, bpm)
keypress("2", x, bpm)
rest(0.235, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.471, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.471, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.471, bpm)
keypress("w", x, bpm)
rest(0.471, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.471, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.471, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.471, bpm)
keypress("6", x, bpm)
rest(0.914, bpm)
keypress("e", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("0", x, bpm)
rest(0.305, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.61, bpm)
keypress("T", x, bpm)
rest(0.305, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.305, bpm)
keypress("e", x, bpm)
rest(0.305, bpm)
keypress("0", x, bpm)
rest(0.305, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("3", x, bpm)
rest(0.305, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("3", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("0", x, bpm)
rest(0.305, bpm)
keypress("e", x, bpm)
rest(0.305, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.08, bpm)
keypress("i", x, bpm)
rest(0.08, bpm)
keypress("p", x, bpm)
rest(0.08, bpm)
keypress("d", x, bpm)
rest(0.217, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.457, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.457, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.457, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.914, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("E", x, bpm)
rest(0.305, bpm)
keypress("e", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("9", x, bpm)
rest(0.305, bpm)
keypress("^", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("2", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.08, bpm)
keypress("i", x, bpm)
rest(0.08, bpm)
keypress("p", x, bpm)
rest(0.08, bpm)
keypress("d", x, bpm)
rest(0.217, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.457, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.457, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("1", x, bpm)
rest(0.229, bpm)
keypress("1", x, bpm)
rest(0.229, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("1", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("t", x, bpm)
rest(0.457, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("w", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("z", x, bpm)
keypress("E", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.457, bpm)
keypress("2", x, bpm)
rest(0.229, bpm)
keypress("2", x, bpm)
rest(0.229, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.114, bpm)
keypress("d", x, bpm)
rest(0.114, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.229, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("1", x, bpm)
keypress("4", x, bpm)
rest(0.305, bpm)
keypress("o", x, bpm)
rest(0.152, bpm)
keypress("q", x, bpm)
rest(0.152, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
rest(0.152, bpm)
keypress("8", x, bpm)
rest(0.152, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.152, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("i", x, bpm)
rest(0.305, bpm)
keypress("t", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("5", x, bpm)
rest(0.305, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.229, bpm)
keypress("y", x, bpm)
rest(0.229, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.229, bpm)
keypress("y", x, bpm)
rest(0.229, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.229, bpm)
keypress("o", x, bpm)
rest(0.229, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
rest(0.229, bpm)
keypress("o", x, bpm)
rest(0.229, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(0.229, bpm)
keypress("p", x, bpm)
rest(0.229, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.229, bpm)
keypress("p", x, bpm)
rest(0.229, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.229, bpm)
keypress("p", x, bpm)
rest(0.229, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.229, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.229, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.229, bpm)
keypress("4", x, bpm)
rest(0.229, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.457, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.457, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.457, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("1", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.229, bpm)
keypress("5", x, bpm)
rest(0.229, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(1.829, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.914, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.229, bpm)
keypress("2", x, bpm)
rest(0.229, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("E", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.914, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("0", x, bpm)
rest(0.457, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.457, bpm)
keypress("e", x, bpm)
rest(0.305, bpm)
keypress("q", x, bpm)
rest(0.305, bpm)
keypress("8", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("4", x, bpm)
rest(0.305, bpm)
keypress("1", x, bpm)
rest(0.305, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.457, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.229, bpm)
keypress("2", x, bpm)
rest(0.229, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.914, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.229, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.229, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("0", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.229, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.229, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.229, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.229, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.914, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("e", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.229, bpm)
keypress("2", x, bpm)
rest(0.229, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("4", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
rest(0.08, bpm)
keypress("i", x, bpm)
rest(0.08, bpm)
keypress("P", x, bpm)
rest(0.08, bpm)
keypress("d", x, bpm)
rest(0.217, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("v", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("0", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.08, bpm)
keypress("i", x, bpm)
rest(0.08, bpm)
keypress("p", x, bpm)
rest(0.08, bpm)
keypress("d", x, bpm)
rest(0.217, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.457, bpm)
keypress("4", x, bpm)
rest(0.457, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.457, bpm)
keypress("8", x, bpm)
rest(0.457, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.457, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.457, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.457, bpm)
keypress("5", x, bpm)
rest(0.457, bpm)
keypress("w", x, bpm)
rest(0.457, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.457, bpm)
keypress("9", x, bpm)
rest(0.457, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.457, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("0", x, bpm)
rest(0.457, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.457, bpm)
keypress("0", x, bpm)
rest(0.457, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.305, bpm)
keypress("a", x, bpm)
rest(0.152, bpm)
keypress("0", x, bpm)
rest(0.152, bpm)
keypress("S", x, bpm)
rest(0.305, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("S", x, bpm)
rest(0.152, bpm)
keypress("6", x, bpm)
rest(0.152, bpm)
keypress("d", x, bpm)
rest(0.305, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("d", x, bpm)
rest(0.305, bpm)
keypress("f", x, bpm)
rest(0.305, bpm)
keypress("g", x, bpm)
rest(0.305, bpm)
keypress("f", x, bpm)
rest(0.305, bpm)
keypress("g", x, bpm)
rest(0.305, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.305, bpm)
keypress("g", x, bpm)
rest(0.305, bpm)
keypress("h", x, bpm)
rest(0.305, bpm)
keypress("j", x, bpm)
rest(0.305, bpm)
keypress("h", x, bpm)
rest(0.305, bpm)
keypress("j", x, bpm)
rest(0.305, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(1.939, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.323, bpm)
keypress("9", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("q", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("9", x, bpm)
rest(0.323, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(0.323, bpm)
keypress("9", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("9", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.323, bpm)
keypress("9", x, bpm)
rest(0.323, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.323, bpm)
keypress("1", x, bpm)
rest(0.323, bpm)
keypress("1", x, bpm)
rest(0.323, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.97, bpm)
keypress("8", x, bpm)
rest(0.323, bpm)
keypress("1", x, bpm)
rest(0.323, bpm)
keypress("5", x, bpm)
rest(0.323, bpm)
keypress("0", x, bpm)
rest(0.323, bpm)
keypress("5", x, bpm)
rest(0.323, bpm)
keypress("8", x, bpm)
rest(0.323, bpm)
keypress("5", x, bpm)
rest(0.323, bpm)
keypress("1", x, bpm)
rest(0.323, bpm)
keypress("5", x, bpm)
rest(0.323, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(1.939, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("0", x, bpm)
rest(1.939, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.97, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("4", x, bpm)
rest(0.485, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.242, bpm)
keypress("t", x, bpm)
rest(0.242, bpm)
keypress("W", x, bpm)
rest(0.242, bpm)
keypress("t", x, bpm)
rest(0.242, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.242, bpm)
keypress("t", x, bpm)
rest(0.242, bpm)
keypress("W", x, bpm)
rest(0.242, bpm)
keypress("t", x, bpm)
rest(0.242, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.242, bpm)
keypress("t", x, bpm)
rest(0.242, bpm)
keypress("W", x, bpm)
rest(0.242, bpm)
keypress("t", x, bpm)
rest(0.242, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.242, bpm)
keypress("i", x, bpm)
rest(0.242, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.242, bpm)
keypress("i", x, bpm)
rest(0.242, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.242, bpm)
keypress("O", x, bpm)
rest(0.242, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.242, bpm)
keypress("O", x, bpm)
rest(0.242, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.242, bpm)
keypress("S", x, bpm)
rest(0.242, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.242, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.242, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("w", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("T", x, bpm)
rest(0.485, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("W", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("W", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("w", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("w", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
rest(0.485, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.485, bpm)
keypress("*", x, bpm)
rest(0.485, bpm)
keypress("Q", x, bpm)
rest(0.485, bpm)
keypress("*", x, bpm)
rest(0.485, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("*", x, bpm)
rest(0.485, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
rest(0.485, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.485, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.485, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("4", x, bpm)
rest(0.485, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.485, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("4", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.485, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.485, bpm)
keypress("8", x, bpm)
rest(0.485, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.242, bpm)
keypress("2", x, bpm)
rest(0.242, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("4", x, bpm)
rest(0.485, bpm)
keypress("(", x, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("4", x, bpm)
rest(0.485, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.485, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.485, bpm)
keypress("@", x, bpm)
rest(0.242, bpm)
keypress("@", x, bpm)
rest(0.242, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.451, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("E", x, bpm)
rest(0.451, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.451, bpm)
keypress("q", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(0.451, bpm)
keypress("q", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.451, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.451, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.451, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("%", x, bpm)
rest(0.451, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
rest(0.451, bpm)
keypress("%", x, bpm)
rest(0.451, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.451, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.3, bpm)
keypress("r", x, bpm)
rest(0.3, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.3, bpm)
keypress("7", x, bpm)
rest(0.3, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("Q", x, bpm)
rest(0.3, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.451, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.079, bpm)
keypress("I", x, bpm)
rest(0.079, bpm)
keypress("P", x, bpm)
rest(0.079, bpm)
keypress("D", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.451, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.451, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.451, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.451, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.451, bpm)
keypress("%", x, bpm)
rest(0.451, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.901, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("%", x, bpm)
rest(0.451, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.451, bpm)
keypress("W", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("3", x, bpm)
rest(0.225, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("r", x, bpm)
rest(0.079, bpm)
keypress("I", x, bpm)
rest(0.079, bpm)
keypress("a", x, bpm)
rest(0.079, bpm)
keypress("D", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.225, bpm)
keypress("!", x, bpm)
rest(0.225, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.451, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
rest(0.225, bpm)
keypress("@", x, bpm)
rest(0.225, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.451, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.079, bpm)
keypress("I", x, bpm)
rest(0.079, bpm)
keypress("a", x, bpm)
rest(0.079, bpm)
keypress("D", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.451, bpm)
keypress("E", x, bpm)
rest(0.3, bpm)
keypress("Q", x, bpm)
rest(0.3, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("^", x, bpm)
rest(0.3, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.079, bpm)
keypress("I", x, bpm)
rest(0.079, bpm)
keypress("a", x, bpm)
rest(0.079, bpm)
keypress("D", x, bpm)
rest(0.214, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.451, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.079, bpm)
keypress("G", x, bpm)
rest(0.079, bpm)
keypress("k", x, bpm)
rest(0.068, bpm)
keypress("!", x, bpm)
rest(0.011, bpm)
keypress("Z", x, bpm)
rest(0.214, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("!", x, bpm)
rest(0.451, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
rest(0.451, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.451, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.079, bpm)
keypress("G", x, bpm)
rest(0.079, bpm)
keypress("k", x, bpm)
rest(0.079, bpm)
keypress("Z", x, bpm)
rest(0.214, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.451, bpm)
keypress("E", x, bpm)
rest(0.3, bpm)
keypress("Q", x, bpm)
rest(0.3, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("^", x, bpm)
rest(0.3, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("!", x, bpm)
rest(0.451, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.451, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("@", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.451, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.3, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.3, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.3, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("3", x, bpm)
rest(0.225, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("r", x, bpm)
rest(0.451, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("$", x, bpm)
rest(0.451, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("!", x, bpm)
rest(0.225, bpm)
keypress("!", x, bpm)
rest(0.225, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.451, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.451, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("@", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.451, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.451, bpm)
keypress("^", x, bpm)
rest(0.451, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.451, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("7", x, bpm)
rest(0.451, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("Y", x, bpm)
keypress("r", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.225, bpm)
keypress("a", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("a", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("Y", x, bpm)
keypress("*", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.225, bpm)
keypress("S", x, bpm)
rest(0.225, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.225, bpm)
keypress("S", x, bpm)
rest(0.225, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.225, bpm)
keypress("O", x, bpm)
rest(0.225, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.225, bpm)
keypress("O", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("P", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.225, bpm)
keypress("P", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
rest(0.225, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("P", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("P", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("P", x, bpm)
rest(0.225, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.225, bpm)
keypress("P", x, bpm)
rest(0.225, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.225, bpm)
keypress("S", x, bpm)
rest(0.225, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.225, bpm)
keypress("S", x, bpm)
rest(0.225, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.225, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("C", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.225, bpm)
keypress("k", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("k", x, bpm)
rest(0.225, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("Z", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("V", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.225, bpm)
keypress("k", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.225, bpm)
keypress("k", x, bpm)
rest(0.225, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.225, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.225, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.225, bpm)
keypress("H", x, bpm)
rest(0.225, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("k", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
rest(0.225, bpm)
keypress("k", x, bpm)
rest(0.225, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("D", x, bpm)
rest(0.225, bpm)
keypress("G", x, bpm)
rest(0.225, bpm)
keypress("C", x, bpm)
keypress("E", x, bpm)
rest(0.225, bpm)
keypress("k", x, bpm)
rest(0.075, bpm)
keypress("Q", x, bpm)
rest(0.15, bpm)
keypress("G", x, bpm)
rest(0.15, bpm)
keypress("*", x, bpm)
rest(0.075, bpm)
keypress("k", x, bpm)
rest(0.225, bpm)
keypress("C", x, bpm)
keypress("^", x, bpm)
rest(0.225, bpm)
keypress("k", x, bpm)
rest(0.075, bpm)
keypress("$", x, bpm)
rest(0.15, bpm)
keypress("G", x, bpm)
rest(0.15, bpm)
keypress("!", x, bpm)
rest(0.075, bpm)
keypress("k", x, bpm)
rest(0.225, bpm)
keypress("B", x, bpm)
keypress("$", x, bpm)
rest(0.225, bpm)
keypress("L", x, bpm)
rest(0.225, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("L", x, bpm)
rest(0.225, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.225, bpm)
keypress("C", x, bpm)
rest(0.225, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(0.225, bpm)
keypress("C", x, bpm)
keypress("3", x, bpm)
rest(0.225, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(1.803, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("I", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("r", x, bpm)
rest(0.516, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("7", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.032, bpm)
keypress("I", x, bpm)
keypress("q", x, bpm)
rest(0.516, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.258, bpm)
keypress("O", x, bpm)
rest(0.129, bpm)
keypress("I", x, bpm)
rest(0.129, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.516, bpm)
keypress("^", x, bpm)
rest(0.516, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("I", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("I", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("*", x, bpm)
rest(0.516, bpm)
keypress("E", x, bpm)
rest(0.516, bpm)
keypress("T", x, bpm)
rest(0.516, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.516, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("O", x, bpm)
rest(0.516, bpm)
keypress("I", x, bpm)
rest(0.129, bpm)
keypress("P", x, bpm)
rest(0.129, bpm)
keypress("O", x, bpm)
rest(0.129, bpm)
keypress("I", x, bpm)
rest(0.129, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.516, bpm)
keypress("(", x, bpm)
rest(0.516, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("I", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(2.065, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(1.032, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.516, bpm)
keypress("i", x, bpm)
rest(0.258, bpm)
keypress("O", x, bpm)
rest(0.129, bpm)
keypress("I", x, bpm)
rest(0.129, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.516, bpm)
keypress("^", x, bpm)
rest(0.516, bpm)
keypress("Q", x, bpm)
rest(3.097, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("*", x, bpm)
rest(0.516, bpm)
keypress("E", x, bpm)
rest(0.516, bpm)
keypress("E", x, bpm)
rest(0.516, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(1.032, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("W", x, bpm)
rest(0.516, bpm)
keypress("7", x, bpm)
rest(0.516, bpm)
keypress("7", x, bpm)
rest(0.516, bpm)
keypress("(", x, bpm)
rest(0.516, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("S", x, bpm)
rest(0.516, bpm)
keypress("P", x, bpm)
rest(1.548, bpm)
keypress("r", x, bpm)
rest(0.516, bpm)
keypress("D", x, bpm)
rest(0.258, bpm)
keypress("P", x, bpm)
rest(0.258, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.516, bpm)
keypress("W", x, bpm)
rest(0.516, bpm)
keypress("T", x, bpm)
rest(0.516, bpm)
keypress("P", x, bpm)
rest(0.258, bpm)
keypress("a", x, bpm)
rest(0.258, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("E", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
rest(0.516, bpm)
keypress("I", x, bpm)
rest(2.581, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("*", x, bpm)
rest(0.516, bpm)
keypress("O", x, bpm)
rest(0.516, bpm)
keypress("E", x, bpm)
rest(0.516, bpm)
keypress("I", x, bpm)
rest(0.516, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("i", x, bpm)
rest(0.516, bpm)
keypress("I", x, bpm)
rest(0.258, bpm)
keypress("i", x, bpm)
rest(0.258, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.516, bpm)
keypress("7", x, bpm)
rest(0.516, bpm)
keypress("(", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(1.032, bpm)
keypress("i", x, bpm)
keypress("r", x, bpm)
rest(2.581, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.516, bpm)
keypress("W", x, bpm)
rest(0.516, bpm)
keypress("T", x, bpm)
rest(0.516, bpm)
keypress("P", x, bpm)
rest(0.258, bpm)
keypress("a", x, bpm)
rest(0.258, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.516, bpm)
keypress("^", x, bpm)
rest(0.516, bpm)
keypress("(", x, bpm)
rest(0.516, bpm)
keypress("^", x, bpm)
rest(0.516, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("^", x, bpm)
rest(0.516, bpm)
keypress("(", x, bpm)
rest(0.516, bpm)
keypress("^", x, bpm)
rest(0.516, bpm)
keypress("q", x, bpm)
keypress("$", x, bpm)
rest(0.344, bpm)
keypress("Q", x, bpm)
rest(0.172, bpm)
keypress("*", x, bpm)
rest(0.172, bpm)
keypress("T", x, bpm)
rest(0.344, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
rest(0.344, bpm)
keypress("I", x, bpm)
rest(0.172, bpm)
keypress("*", x, bpm)
rest(0.172, bpm)
keypress("S", x, bpm)
rest(0.344, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.516, bpm)
keypress("*", x, bpm)
rest(0.516, bpm)
keypress("Q", x, bpm)
rest(0.516, bpm)
keypress("T", x, bpm)
rest(0.516, bpm)
keypress("$", x, bpm)
rest(0.516, bpm)
keypress("Q", x, bpm)
rest(1.032, bpm)
keypress("$", x, bpm)
rest(0.516, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1.185, bpm)
keypress("7", x, bpm)
rest(1.185, bpm)
keypress("(", x, bpm)
rest(1.185, bpm)
keypress("Q", x, bpm)
rest(1.185, bpm)
keypress("r", x, bpm)
rest(0.593, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.593, bpm)
keypress("I", x, bpm)
rest(0.593, bpm)
keypress("Y", x, bpm)
rest(0.593, bpm)
keypress("I", x, bpm)
rest(0.593, bpm)
keypress("Y", x, bpm)
rest(2.37, bpm)
keypress("Y", x, bpm)
rest(0.593, bpm)
keypress("I", x, bpm)
rest(0.593, bpm)
keypress("Y", x, bpm)
rest(0.593, bpm)
keypress("I", x, bpm)
rest(0.593, bpm)
keypress("Y", x, bpm)
rest(2.37, bpm)
keypress("D", x, bpm)
rest(0.593, bpm)
keypress("G", x, bpm)
rest(0.593, bpm)
keypress("D", x, bpm)
rest(0.593, bpm)
keypress("G", x, bpm)
rest(0.593, bpm)
keypress("D", x, bpm)
rest(2.37, bpm)
keypress("D", x, bpm)
rest(0.593, bpm)
keypress("G", x, bpm)
rest(0.593, bpm)
keypress("D", x, bpm)
rest(0.593, bpm)
keypress("G", x, bpm)
rest(0.593, bpm)
keypress("D", x, bpm)

finishedSong()