keypress("g", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("z", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.533, bpm)
keypress("^", x, bpm)
rest(0.533, bpm)
keypress("l", x, bpm)
rest(0.571, bpm)
keypress("(", x, bpm)
rest(0.571, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(1.231, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(2.909, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
rest(3, bpm)
keypress("^", x, bpm)

finishedSong()